# Generated by Django 6.0.2 on 2026-02-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], max_length=5, verbose_name='Мова')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я фільму")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис фільму')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Картинка фільму')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Посилання на трейлер')),
                ('company', models.CharField(max_length=255, verbose_name='Виробник')),
                ('duration', models.CharField(max_length=50, verbose_name='Тривалість')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cinema.product')),
            ],
            options={
                'unique_together': {('product', 'lang')},
            },
        ),
    ]
