# Generated by Django 6.0.2 on 2026-02-27 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Оновлено'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Оновлено'),
        ),
    ]
