# Generated by Django 6.0.2 on 2026-02-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Рік'),
        ),
    ]
