# Generated by Django 6.0.2 on 2026-02-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_product_is_active_product_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Рік'),
        ),
    ]
